default:
  image: ubuntu:rolling
  before_script:
    - apt-get update
    - apt-get install -y apt-utils build-essential sudo git libboost-all-dev

build-job:
  stage: build
  script:
    - make dist
  
test-job1:
  stage: test
  script:
    - make ci

test-job2:
  stage: test
  script:
    - make test
