default:
  image: archlinux:latest
  before_script:
    - pacman -Syu 
    - pacman -S gcc
    - pacman -S boost

build-job:
  stage: build
  script:
    - make dist
  
test-job1:
  stage: test
  script:
    - make ci

test-job2:
  stage: test
  script:
    - make test
