default:
  image: archlinux:latest
  before_script:
    - pacman --noconfirm -Syu 
    - pacman --noconfirm -S base-devel
    - pacman --noconfirm -S gcc
    - pacman --noconfirm -S boost

build-job:
  stage: build
  script:
    - make dist
  artifacts:
    when: always
    paths:
      - riscv_dist.run
  
test-job:
  stage: test
  script:
    - make ci
  artifacts:
    when: always
    paths:
      - ./test_report.xml
    reports:
      junit: ./test_report.xml
